include:
  - board: corneish_zen_left/nrf52840/zmk
  - board: corneish_zen_right/nrf52840/zmk
  - board: corneish_zen_left/nrf52840/zmk
    snippet: studio-rpc-usb-uart
    artifact-name: corneish_zen_left_with_studio
